//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiSP
    {
        public LoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
        [Display(Name = "Mã LoạiSản Phẩm")]
        public int MaLoaiSP { get; set; }
        [Display(Name = "Tên Loại Sản Phẩm")]
        public string TenLoaiSP { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
