//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public Nhanvien()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaNV { get; set; }
        public string HoNV { get; set; }
        public string Ten { get; set; }
        public string Diachi { get; set; }
        public string Dienthoai { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
