//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        public SanPham()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        [Display(Name = "Mã Sản Phẩm")]
        public string MaSP { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        public string TenSP { get; set; }
        [Display(Name = "Đơn Vị Tính")]
        public string Donvitinh { get; set; }
        [Display(Name = "Đơn Giá")]
        public Nullable<double> Dongia { get; set; }
        [Display(Name = "Loại Sản Phẩm")]
        public Nullable<int> MaLoaiSP { get; set; }
        [Display(Name = "Hình Sản Phẩm")]
        public string HinhSP { get; set; }
    
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
